stages:
  - builds
  - run
  - tests
  - cleanup

# Run for all stages
before_script:
  - echo Cache directory set to ${CACHE_DIR:=/lustre/f2/scratch/oar.gfdl.ogrp-account/runner/cache/}
  # Install / update testing scripts
  - git clone https://github.com/adcroft/MRS.git MRS
  - (cd MRS ; git checkout xanadu-fms)
  # Recursively clone submodules
  - git submodule sync --recursive && git submodule update --init --recursive
  # Clone other components
  - test -d MOM6-examples/src/LM3 || make -f MRS/Makefile.clone clone_gfdl -s
  # Link to datasets
  - make -f MRS/Makefile.clone MOM6-examples/.datasets -s

# Compiles
gnu:repro:
  stage: builds
  tags:
    - ncrc3
  script:
    - time make -f MRS/Makefile.build build_gnu -s -j
    - time make -f MRS/Makefile.build static_gnu -s -j
    - time tar zvcf $CACHE_DIR/build-gnu-repro-$CI_PIPELINE_ID.tgz `find build/gnu -name MOM6`

intel:repro:
  stage: builds
  tags:
    - ncrc3
  script:
    - make -f MRS/Makefile.build build_intel -s -j
    - time tar zvcf $CACHE_DIR/build-intel-repro-$CI_PIPELINE_ID.tgz `find build/intel -name MOM6`

pgi:repro:
  stage: builds
  tags:
    - ncrc3
  script:
    - make -f MRS/Makefile.build build_pgi -s -j
    - time tar zvcf $CACHE_DIR/build-pgi-repro-$CI_PIPELINE_ID.tgz `find build/pgi -name MOM6`

gnu:debug:
  stage: builds
  tags:
    - ncrc3
  script:
    - make -f MRS/Makefile.build debug_gnu -s -j
    - time tar zvcf $CACHE_DIR/build-gnu-debug-$CI_PIPELINE_ID.tgz `find build/gnu -name MOM6`

# Runs
run:
  stage: run
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/build-gnu-repro-$CI_PIPELINE_ID.tgz
    - time tar zxf $CACHE_DIR/build-intel-repro-$CI_PIPELINE_ID.tgz
    - time tar zxf $CACHE_DIR/build-pgi-repro-$CI_PIPELINE_ID.tgz
    - time tar zxf $CACHE_DIR/build-gnu-debug-$CI_PIPELINE_ID.tgz
    - (echo '#!/bin/tcsh';echo 'make -f MRS/Makefile.tests all -B') > job.sh
    - sbatch --clusters=c3,c4 --nodes=30 --time=0:42:00 --account=gfdl_o --qos=debug --job-name=mom6_full_regression --output=log.$CI_PIPELINE_ID --wait job.sh
    - cat log.$CI_PIPELINE_ID
    - test -f restart_results_gnu.tar.gz
    - time tar zvcf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz *.tar.gz

# Tests
gnu:non-symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests gnu_non_symmetric

intel:non-symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests intel_non_symmetric

pgi:non-symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests pgi_non_symmetric

gnu:symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests gnu_symmetric

intel:symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests intel_symmetric

pgi:symmetric:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests pgi_symmetric

gnu:layout:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests gnu_layout

intel:layout:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests intel_layout

pgi:layout:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests pgi_layout

gnu:static:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests gnu_static

gnu:restart:
  stage: tests
  tags:
    - ncrc3
  script:
    - time tar zxf $CACHE_DIR/results-$CI_PIPELINE_ID.tgz
    - make -f MRS/Makefile.tests gnu_check_restarts

cleanup:
  stage: cleanup
  tags:
    - ncrc3
  script:
    - rm $CACHE_DIR/*$CI_PIPELINE_ID.tgz
